#! /bin/sh

pkill sxhkd
sxhkd &

#pkill compton
#compton &

pkill picom
picom --experimental-backends &

pkill dunst
dunst &

pkill polybar
polybar mybar &

xautolock -locker "gllock"
xsetroot -cursor_name left_ptr
feh --bg-scale ~/pictures/wallpaper/fuji.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color	  "#292d3e"
bspc config active_border_color   "#ffcc01"
bspc config focused_border_color  "#bfc7d5"
bspc config presel_feedback_color "#ffcc01"

bspc config border_width  2
bspc config window_gap   16

bspc config split_ratio        0.5
bspc config borderless_monocle false
bspc config gapless_monocle    true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
